clone:
  git:
    image: registry.fpfis.eu/drone-plugins/git:next
    when:
      event: [ push, pull_request, tag ]
  git:
    image: registry.fpfis.eu/drone-plugins/git
    when:
      event: [ deployment ]

workspace:
  base: /test
  path: oe_content

services:
  web:
    image: registry.fpfis.eu/fpfis/httpd-php:${PHP_VERSION}-ci
    environment:
      - DOCUMENT_ROOT=/test/oe_content
  mysql:
    image: registry.fpfis.eu/fpfis/sql:percona-5.7
    command: --innodb-log-file-size=1G --max_allowed_packet=1G --innodb-buffer-pool-size=512M --wait_timeout=3000 --net_write_timeout=3000 --log_error_verbosity=3
    environment:
      - MYSQL_ALLOW_EMPTY_PASSWORD=yes
  sparql:
    # Temporarily fix the triple store version to avoid "Provisional data" terms.
    # @todo: Use the latest release once a solution for the "Provisional data" terms is implemented.
    image: registry.fpfis.eu/openeuropa/triple-store-dev:1.14.0
    pull: true
    environment:
      - SPARQL_UPDATE=true
      - DBA_PASSWORD=dba
  selenium:
    image: registry.fpfis.eu/fpfis/selenium:standalone-chrome-3.141.59-oxygen
    pull: true
    shm_size: 2g
    environment:
      - DISPLAY=:99
      - SE_OPTS=-debug
      - SCREEN_WIDTH=1280
      - SCREEN_HEIGHT=800

pipeline:
  composer-install-lowest:
    group: prepare
    image: registry.fpfis.eu/fpfis/httpd-php:${PHP_VERSION}-ci
    volumes:
      - /cache:/cache
    commands:
      # @todo remove "composer install" step once the following issue is fixed.
      # @link https://webgate.ec.europa.eu/CITnet/jira/browse/OPENEUROPA-1234
      - composer install --ansi --no-suggest --no-progress
      - composer update --prefer-lowest --prefer-stable --ansi --no-suggest --no-progress
    when:
      matrix:
        COMPOSER_BOUNDARY: lowest

  composer-install-highest:
    group: prepare
    image: registry.fpfis.eu/fpfis/httpd-php:${PHP_VERSION}-ci
    volumes:
      - /cache:/cache
    commands:
      - composer install --ansi --no-suggest --no-progress
    when:
      matrix:
        COMPOSER_BOUNDARY: highest

  site-install:
    image: registry.fpfis.eu/fpfis/httpd-php:${PHP_VERSION}-ci
    commands:
      - ./vendor/bin/run drupal:site-install
    when:
      matrix:
        TYPE: behat

  grumphp:
    group: test
    image: registry.fpfis.eu/fpfis/httpd-php:${PHP_VERSION}-ci
    commands:
      - ./vendor/bin/grumphp run
    when:
      matrix:
        COMPOSER_BOUNDARY: highest
        TYPE: phpunit

  phpunit:
    group: test
    image: registry.fpfis.eu/fpfis/httpd-php:${PHP_VERSION}-ci
    commands:
      - ./vendor/bin/phpunit
    when:
      matrix:
        TYPE: phpunit

  behat:
    group: test
    image: registry.fpfis.eu/fpfis/httpd-php:${PHP_VERSION}-ci
    commands:
      - ./vendor/bin/behat --strict --tags=$BATCH
    when:
      matrix:
        TYPE: behat

  debug:
    image: registry.fpfis.eu/fpfis/httpd-php:${PHP_VERSION}-ci
    commands:
      - ./vendor/bin/drush ws --count 500
    when:
      status: failure

matrix:
  include:
    - { PHP_VERSION: 7.3, COMPOSER_BOUNDARY: lowest, TYPE: phpunit }
    - { PHP_VERSION: 7.3, COMPOSER_BOUNDARY: lowest, TYPE: behat, BATCH: '@batch1' }
    - { PHP_VERSION: 7.3, COMPOSER_BOUNDARY: lowest, TYPE: behat, BATCH: '@batch2' }
    - { PHP_VERSION: 7.3, COMPOSER_BOUNDARY: lowest, TYPE: behat, BATCH: '@batch3' }

    - { PHP_VERSION: 7.3, COMPOSER_BOUNDARY: highest, TYPE: phpunit }
    - { PHP_VERSION: 7.3, COMPOSER_BOUNDARY: highest, TYPE: behat, BATCH: '@batch1' }
    - { PHP_VERSION: 7.3, COMPOSER_BOUNDARY: highest, TYPE: behat, BATCH: '@batch2' }
    - { PHP_VERSION: 7.3, COMPOSER_BOUNDARY: highest, TYPE: behat, BATCH: '@batch3' }
