field.field_settings.oe_featured_media:
  type: field.field_settings.entity_reference
  label: 'Featured media field settings'

field.storage_settings.oe_featured_media:
  type: field.storage_settings.entity_reference
  label: 'Featured media field storage settings'

field.value.oe_featured_media:
  type: mapping
  label: 'Default value'
  mapping:
    target_id:
      type: integer
      label: 'Target entity ID'
    target_uuid:
      type: uuid
    caption:
      type: text
      label: 'Caption value'

field.formatter.settings.oe_featured_media_label:
  type: field.formatter.settings.entity_reference_label

field.widget.settings.oe_featured_media_autocomplete:
  type: field.widget.settings.entity_reference_autocomplete
